service: functions
configValidationMode: off
singleSource: false

useDotenv: true

provider:
  name: scaleway
  runtime: node18
  env:
    NODE_ENV: production
  secret:
    PROJECT_KEY: ${env:PROJECT_KEY}
  
  scwToken: ${env:SCW_TOKEN}
  scwProject: ${env:SCW_PROJECT}
  # region in which the deployment will happen (default: fr-par)
  scwRegion: nl-ams

plugins:
  - serverless-scaleway-functions

package:
  patterns:
    - '!.gitignore'
    - '!.git/**'
    - '!*.sh'
    - 'node_modules/**'
    - '!functions/**'
    - '!helper/**'
    - '!.env'
    - '!tsconfig.json'
    - '!test/**'
    - '!debug-server'
    - '!build/debug-server'
    - '!build/test/**'

functions:
  new-key-required:
    handler: build/functions/hasNewKey.handler
  
  sign:
    handler: build/functions/sign.handler

  get-new-key:
    handler: build/functions/getNewKey.handler
