name: Test on push
on:
    pull_request:
        branches:
            - main
            - dev
jobs: 
 build:
  environment:
    name: dev
  runs-on: ubuntu-latest
  steps:
    - name: Convert secrets to env vars
      uses: Firenza/secrets-to-env@v1.2.0
      with:
        secrets: ${{ toJSON(secrets) }}

    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Setup Go 1.21.x
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    
    - name: Install all dependencies
      run: cd ${{github.workspace}}/scw_secret_wrapper && go get . && cd ${{github.workspace}}/helper && go get . && cd ${{github.workspace}}/sign && go get . && cd ${{github.workspace}}/cronjob && go get .

    - name: Sign tests
      run: cd ${{github.workspace}}/sign && go test -v
    
    - name: Run scw_secret_wrapper tests
      run: cd ${{github.workspace}}/scw_secret_wrapper && go test ./... -v
    
    - name: Run helper tests
      run: cd ${{github.workspace}}/helper && go test -v
    
    - name: Run cronjob tests
      run: cd ${{github.workspace}}/cronjob && go test -v
    